### ISSUE TITLE
Баг с определением филиала

### ISSUE THREAD

**Issue by OlegVo** [klpx/webapi-tools#2]
http://catalog.api.2gis.ru/2.0/catalog/branch/search?page=1&page_size=12&q=%D0%9F%D0%BE%D0%B5%D1%81%D1%82%D1%8C&region_id=1&key=rucipq3137

У первого филиала id=70000001006936913. Расширение определяет его как 70000001006936910.

**Comment by klpx** [comment]
Старая добрая проблема :)
